
/*  Le code HTML commence ici! */
<template>
    <div class="content">
    	<!-- Ajoutez des balises HTML juste en dessous-->
    	<h1>ROCKET LEAGUE</h1>
    	<p>ROCKET LEAGUE EST UNE JEUX DE VOITURE ET DE FOOT IL Y A DES 
      CLASSEMENT ET DES COMPETE ET DES TOURNOISIL ET DES OCCASIONEL IL Y A TOUJOURES 5 MINUTE
       DE JEUX APAR SI IL Y A LES PROLONGATION IL Y A UN TURBO DE 100 EST QAND TU L UTTILISE
       IL I ON A PLUS MAIS TU PEUX ON REPRONDRQUAND TU VA SUR UN BOOST QUAND TU 
       PREND LE GRAND TU PREND 100 DE BOOST ET QUAND TU PREND LE PETIT TU PREND 15
       DE BOOST ET QAND TU JOUE A COMET TU JOUE CONTRE DES VRAIS PERSSONE ET IL Y A 
       DES RANGS ET IL Y A DES NIVEAU COMME AU TOUT DEBUT TU EST CLASSE NON CLASSE APRES TU ES BRONZE 
      ARGENT OR PLATINE ECT IL Y A UN TRES GRAND BALLON EST PLUSIEURES MAP 
      OU STYL DE JEUX COMME FOOTCAR OU GHUIDACHE OU RUMBLE EST A MULTIJOUEURE 
      TU PEUX JOUER ENTRE AMIS MAIS MOI JE JOUE TOUT SOEUL TU PEUX JOUER A 2VS2 OU 1V1 OU 3V3 TUPEUX PERSONNALLISER
      TA VOITURE AVEC PLUSIEURES SKINE TU PEUX METTRE DES CHAPEAU OU DES COULEURES DE VIOTURE IL Y A AUSSI LE PASSE DE COMBAT 
      TU PEUX AUSSI GAGNER DES BOITES ET DEDANS TU PEUX GAGNER AUSSI DES STILE DE VOITURE DES CAPEAU ECT 
      ET QAND TU MARCKE TU PEUX ACHETE DES CELEBRATION ET TU PEUX AUSSI ACHETE DES CREDIT 
      POURE ACHETE DES VOITURE ET PLUSIERES AUTRES OBJETET PARFOIS QUAND TU MARKE OU ARRETE UN TIRE OU FAIRE UNE PASSE D  TU GAGNE DES PORCENT  
      ET CE LUI QUI GAGNE LA PARTIE ET A LE PLUS DE PORCENT TU ES ELU LE MEILLEURE JOUERDU DE LE PARTIE 
      ON PEUT JOUER SUR PLAY XBOX ECT LE JEUE EST GRATUIT PORE L INSTANT. 
      </p>
    </div>
</template>
/* Le code HTML se finit ici... */





/* Le code CSS commence ici! */
<style scoped> 

	.content {
		height : 100vh;
		background-color : black
	}

  h1{
    margin : 0;
    color : darkgreen;
  }

  p{
    color: blue;
  }

</style>
/* Le code CSS se finit ici... */
